# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-05 08:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parpol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('keterangan', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('nomor_urut', models.IntegerField(default=0, max_length=255)),
                ('parpol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pemilu.Parpol')),
            ],
        ),
    ]
