# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-05 09:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pemilu', '0003_president_wakilpresident'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terpilih',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pemilu.President')),
                ('cawapress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pemilu.WakilPresident')),
            ],
        ),
    ]
